version = 0.1
[default.deploy.parameters]
stack_name = "waterfall-artworks-service"
resolve_s3 = true
s3_prefix = "waterfall-artworks-service"
region = "ca-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
