AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  WaterfallArtworksService:
    Type: AWS::Serverless::Api
    Description: "Serverless API for Waterfall"
    Properties:
      Name: "waterfall-artworks-service"
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS, GET'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'https://waterfall.phil-code.com'" 
        # AllowOrigin: "'http://localhost:3000'" 

  WaterfallArtworksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: dist/index.lambdaHandler
      Layers:
      - arn:aws:lambda:ca-central-1:950671533172:layer:canvas-layer:1
      Runtime: nodejs22.x

      CodeUri: .
      Policies:
        - AWSLambdaExecute
        - SecretsManagerReadWrite
      Events:
        ArtworksOptions:
          Type: Api
          Properties:
            Path: /artworks
            Method: OPTIONS
            RestApiId: !Ref WaterfallArtworksService
        GetArtwork:
          Type: Api
          Properties:
            Path: /artworks/{artworkId}
            Method: GET
            RestApiId: !Ref WaterfallArtworksService
        GetArtworks:
          Type: Api
          Properties:
            Path: /artworks/random/{departmentId}
            Method: GET
            RestApiId: !Ref WaterfallArtworksService
        
    Metadata:
      BuildMethod: makefile
